/* This file is automatically generated by tool/char_trait.pl */
typedef struct {
    const char* entity;
    size_t      entity_len;
} entity_t;

static const entity_t amp  = { STR_WITH_LEN("&amp;")  };
static const entity_t gt   = { STR_WITH_LEN("&gt;")   };
static const entity_t lt   = { STR_WITH_LEN("&lt;")   };
static const entity_t quot = { STR_WITH_LEN("&quot;") };
static const entity_t apos = { STR_WITH_LEN("&apos;") };

static const entity_t* const char_trait[] = {
    NULL , /* \x 0 */
    NULL , /* \x 1 */
    NULL , /* \x 2 */
    NULL , /* \x 3 */
    NULL , /* \x 4 */
    NULL , /* \x 5 */
    NULL , /* \x 6 */
    NULL , /* \x 7 */
    NULL , /* \x 8 */
    NULL , /* \x 9 */
    NULL , /* \x a */
    NULL , /* \x b */
    NULL , /* \x c */
    NULL , /* \x d */
    NULL , /* \x e */
    NULL , /* \x f */
    NULL , /* \x10 */
    NULL , /* \x11 */
    NULL , /* \x12 */
    NULL , /* \x13 */
    NULL , /* \x14 */
    NULL , /* \x15 */
    NULL , /* \x16 */
    NULL , /* \x17 */
    NULL , /* \x18 */
    NULL , /* \x19 */
    NULL , /* \x1a */
    NULL , /* \x1b */
    NULL , /* \x1c */
    NULL , /* \x1d */
    NULL , /* \x1e */
    NULL , /* \x1f */
    NULL , /*   */
    NULL , /* ! */
    &quot, /* " */
    NULL , /* # */
    NULL , /* $ */
    NULL , /* % */
    &amp , /* & */
    &apos, /* ' */
    NULL , /* ( */
    NULL , /* ) */
    NULL , /* * */
    NULL , /* + */
    NULL , /* , */
    NULL , /* - */
    NULL , /* . */
    NULL , /* / */
    NULL , /* 0 */
    NULL , /* 1 */
    NULL , /* 2 */
    NULL , /* 3 */
    NULL , /* 4 */
    NULL , /* 5 */
    NULL , /* 6 */
    NULL , /* 7 */
    NULL , /* 8 */
    NULL , /* 9 */
    NULL , /* : */
    NULL , /* ; */
    &lt  , /* < */
    NULL , /* = */
    &gt  , /* > */
    NULL , /* ? */
    NULL , /* @ */
    NULL , /* A */
    NULL , /* B */
    NULL , /* C */
    NULL , /* D */
    NULL , /* E */
    NULL , /* F */
    NULL , /* G */
    NULL , /* H */
    NULL , /* I */
    NULL , /* J */
    NULL , /* K */
    NULL , /* L */
    NULL , /* M */
    NULL , /* N */
    NULL , /* O */
    NULL , /* P */
    NULL , /* Q */
    NULL , /* R */
    NULL , /* S */
    NULL , /* T */
    NULL , /* U */
    NULL , /* V */
    NULL , /* W */
    NULL , /* X */
    NULL , /* Y */
    NULL , /* Z */
    NULL , /* [ */
    NULL , /* \ */
    NULL , /* ] */
    NULL , /* ^ */
    NULL , /* _ */
    NULL , /* ` */
    NULL , /* a */
    NULL , /* b */
    NULL , /* c */
    NULL , /* d */
    NULL , /* e */
    NULL , /* f */
    NULL , /* g */
    NULL , /* h */
    NULL , /* i */
    NULL , /* j */
    NULL , /* k */
    NULL , /* l */
    NULL , /* m */
    NULL , /* n */
    NULL , /* o */
    NULL , /* p */
    NULL , /* q */
    NULL , /* r */
    NULL , /* s */
    NULL , /* t */
    NULL , /* u */
    NULL , /* v */
    NULL , /* w */
    NULL , /* x */
    NULL , /* y */
    NULL , /* z */
    NULL , /* { */
    NULL , /* | */
    NULL , /* } */
    NULL , /* ~ */
    NULL , /* \x7f */
    NULL , /* \x80 */
    NULL , /* \x81 */
    NULL , /* \x82 */
    NULL , /* \x83 */
    NULL , /* \x84 */
    NULL , /* \x85 */
    NULL , /* \x86 */
    NULL , /* \x87 */
    NULL , /* \x88 */
    NULL , /* \x89 */
    NULL , /* \x8a */
    NULL , /* \x8b */
    NULL , /* \x8c */
    NULL , /* \x8d */
    NULL , /* \x8e */
    NULL , /* \x8f */
    NULL , /* \x90 */
    NULL , /* \x91 */
    NULL , /* \x92 */
    NULL , /* \x93 */
    NULL , /* \x94 */
    NULL , /* \x95 */
    NULL , /* \x96 */
    NULL , /* \x97 */
    NULL , /* \x98 */
    NULL , /* \x99 */
    NULL , /* \x9a */
    NULL , /* \x9b */
    NULL , /* \x9c */
    NULL , /* \x9d */
    NULL , /* \x9e */
    NULL , /* \x9f */
    NULL , /* \xa0 */
    NULL , /* \xa1 */
    NULL , /* \xa2 */
    NULL , /* \xa3 */
    NULL , /* \xa4 */
    NULL , /* \xa5 */
    NULL , /* \xa6 */
    NULL , /* \xa7 */
    NULL , /* \xa8 */
    NULL , /* \xa9 */
    NULL , /* \xaa */
    NULL , /* \xab */
    NULL , /* \xac */
    NULL , /* \xad */
    NULL , /* \xae */
    NULL , /* \xaf */
    NULL , /* \xb0 */
    NULL , /* \xb1 */
    NULL , /* \xb2 */
    NULL , /* \xb3 */
    NULL , /* \xb4 */
    NULL , /* \xb5 */
    NULL , /* \xb6 */
    NULL , /* \xb7 */
    NULL , /* \xb8 */
    NULL , /* \xb9 */
    NULL , /* \xba */
    NULL , /* \xbb */
    NULL , /* \xbc */
    NULL , /* \xbd */
    NULL , /* \xbe */
    NULL , /* \xbf */
    NULL , /* \xc0 */
    NULL , /* \xc1 */
    NULL , /* \xc2 */
    NULL , /* \xc3 */
    NULL , /* \xc4 */
    NULL , /* \xc5 */
    NULL , /* \xc6 */
    NULL , /* \xc7 */
    NULL , /* \xc8 */
    NULL , /* \xc9 */
    NULL , /* \xca */
    NULL , /* \xcb */
    NULL , /* \xcc */
    NULL , /* \xcd */
    NULL , /* \xce */
    NULL , /* \xcf */
    NULL , /* \xd0 */
    NULL , /* \xd1 */
    NULL , /* \xd2 */
    NULL , /* \xd3 */
    NULL , /* \xd4 */
    NULL , /* \xd5 */
    NULL , /* \xd6 */
    NULL , /* \xd7 */
    NULL , /* \xd8 */
    NULL , /* \xd9 */
    NULL , /* \xda */
    NULL , /* \xdb */
    NULL , /* \xdc */
    NULL , /* \xdd */
    NULL , /* \xde */
    NULL , /* \xdf */
    NULL , /* \xe0 */
    NULL , /* \xe1 */
    NULL , /* \xe2 */
    NULL , /* \xe3 */
    NULL , /* \xe4 */
    NULL , /* \xe5 */
    NULL , /* \xe6 */
    NULL , /* \xe7 */
    NULL , /* \xe8 */
    NULL , /* \xe9 */
    NULL , /* \xea */
    NULL , /* \xeb */
    NULL , /* \xec */
    NULL , /* \xed */
    NULL , /* \xee */
    NULL , /* \xef */
    NULL , /* \xf0 */
    NULL , /* \xf1 */
    NULL , /* \xf2 */
    NULL , /* \xf3 */
    NULL , /* \xf4 */
    NULL , /* \xf5 */
    NULL , /* \xf6 */
    NULL , /* \xf7 */
    NULL , /* \xf8 */
    NULL , /* \xf9 */
    NULL , /* \xfa */
    NULL , /* \xfb */
    NULL , /* \xfc */
    NULL , /* \xfd */
    NULL , /* \xfe */
    NULL , /* \xff */
}; /* trait[] */
/* EOF */
