#!perl -w
use 5.10.0;
use strict;
use bytes;

print <<"H";
/* This file is automatically generated by $0 */
H

print <<'H';
typedef struct {
    const char* entity;
    size_t      entity_len;
} entity_t;

static const entity_t amp  = { STR_WITH_LEN("&amp;")  };
static const entity_t gt   = { STR_WITH_LEN("&gt;")   };
static const entity_t lt   = { STR_WITH_LEN("&lt;")   };
static const entity_t quot = { STR_WITH_LEN("&quot;") };
static const entity_t apos = { STR_WITH_LEN("&apos;") };

static const entity_t* const char_trait[] = {
H
my %esc = (
    q{&} => '&amp',
    q{>} => '&gt',
    q{<} => '&lt',
    q{"} => '&quot',
    q{'} => '&apos',
);

for my $c(0x00 .. 0xFF) {
    my $char = chr $c;

    my $entity = $esc{$char};
    printf "    %-5s,", $esc{$char} // "NULL";
    if($char =~ /[[:print:]]/) {
        print " /* $char */";
    }
    else {
        printf ' /* \x%2x */', $c;
    }
    print "\n";
}

print <<'H';
}; /* trait[] */
/* EOF */
H
